import { and, eq } from "drizzle-orm";
import { db, schema } from "@/lib/db";
import type { InvoiceTemplateConfig } from "./schema";

export type InvoiceTemplateLayout = "clean" | "bold" | "classic" | "receipt";

export type InvoiceTemplatePreset = {
  key: string;
  name: string;
  layout: InvoiceTemplateLayout;
  isDefault: boolean;
  description: string;
  config: InvoiceTemplateConfig;
};

export const INVOICE_TEMPLATE_LAYOUTS: Array<{
  value: InvoiceTemplateLayout;
  label: string;
}> = [
  { value: "clean", label: "Modern" },
  { value: "bold", label: "Bold" },
  { value: "classic", label: "Classic" },
  { value: "receipt", label: "Receipt" },
];

export const INVOICE_TEMPLATE_PRESETS: InvoiceTemplatePreset[] = [
  {
    key: "modern",
    name: "Modern",
    layout: "clean",
    isDefault: true,
    description: "Airy, polished invoice with a strong balance section.",
    config: {
      brandColor: "#0f172a",
      accentColor: "#0d9488",
      fontFamily: "sans",
      showLogo: true,
      headerText: "Thank you for choosing {{org.name}}.",
      footerText: "Questions? Reply to this invoice and we will help.",
      termsText: "Payment is due by {{invoice.dueDate}}.",
      showTaxBreakdown: true,
      showPaymentInstructions: true,
      paymentInstructions: "Please include invoice {{invoice.number}} with your payment.",
      dateFormat: "us",
      showDueDate: true,
      showOrderNumber: true,
    },
  },
  {
    key: "bold",
    name: "Bold",
    layout: "bold",
    isDefault: false,
    description: "High-contrast header for confident branded invoices.",
    config: {
      brandColor: "#111827",
      accentColor: "#f97316",
      fontFamily: "sans",
      showLogo: true,
      footerText: "{{org.name}} appreciates your business.",
      termsText: "Balance due: {{invoice.balance}}.",
      showTaxBreakdown: true,
      showPaymentInstructions: true,
      paymentInstructions: "Send payment with invoice number {{invoice.number}}.",
      dateFormat: "us",
      showDueDate: true,
      showOrderNumber: true,
    },
  },
  {
    key: "classic",
    name: "Classic",
    layout: "classic",
    isDefault: false,
    description: "Formal business invoice with restrained internal dividers.",
    config: {
      brandColor: "#1f2937",
      accentColor: "#2563eb",
      fontFamily: "serif",
      showLogo: true,
      footerText: "Thank you for your prompt payment.",
      termsText: "Payment due by {{invoice.dueDate}}.",
      showTaxBreakdown: true,
      showPaymentInstructions: false,
      dateFormat: "us",
      showDueDate: true,
      showOrderNumber: true,
    },
  },
  {
    key: "receipt",
    name: "Receipt",
    layout: "receipt",
    isDefault: false,
    description: "Compact receipt-style layout for quick confirmations.",
    config: {
      brandColor: "#334155",
      accentColor: "#059669",
      fontFamily: "mono",
      showLogo: true,
      footerText: "Receipt generated by {{org.name}}.",
      termsText: "Paid or payable balance: {{invoice.balance}}.",
      showTaxBreakdown: true,
      showPaymentInstructions: false,
      dateFormat: "us",
      showDueDate: true,
      showOrderNumber: true,
    },
  },
];

export function getPresetByName(name: string) {
  return INVOICE_TEMPLATE_PRESETS.find(
    (preset) => preset.name.toLowerCase() === name.trim().toLowerCase(),
  );
}

export async function ensureInvoiceTemplatePresets(orgId: string) {
  const templates = await db
    .select({
      id: schema.invoiceTemplates.id,
      name: schema.invoiceTemplates.name,
      layout: schema.invoiceTemplates.layout,
      isDefault: schema.invoiceTemplates.isDefault,
    })
    .from(schema.invoiceTemplates)
    .where(eq(schema.invoiceTemplates.orgId, orgId));

  const hasDefault = templates.some((template) => template.isDefault);
  const hasLegacyOnlyDefault =
    templates.length === 1 &&
    templates[0]?.layout === "clean" &&
    templates[0]?.name.toLowerCase() === "default";

  if (hasLegacyOnlyDefault) {
    const modern = INVOICE_TEMPLATE_PRESETS[0];
    await db
      .update(schema.invoiceTemplates)
      .set({
        name: modern.name,
        layout: modern.layout,
        isDefault: true,
        config: modern.config,
        updatedAt: new Date(),
      })
      .where(
        and(
          eq(schema.invoiceTemplates.orgId, orgId),
          eq(schema.invoiceTemplates.id, templates[0].id),
        ),
      );
    templates[0] = {
      id: templates[0].id,
      name: modern.name,
      layout: modern.layout,
      isDefault: true,
    };
  }

  const existingNames = new Set(templates.map((template) => template.name.toLowerCase()));
  const rowsToInsert = INVOICE_TEMPLATE_PRESETS.filter(
    (preset) => !existingNames.has(preset.name.toLowerCase()),
  ).map((preset) => ({
    orgId,
    name: preset.name,
    layout: preset.layout,
    isDefault: preset.isDefault && !hasDefault,
    config: preset.config,
  }));

  if (rowsToInsert.length > 0) {
    await db.insert(schema.invoiceTemplates).values(rowsToInsert);
  }

  if (!hasDefault && !rowsToInsert.some((row) => row.isDefault)) {
    const modern = await db
      .select({ id: schema.invoiceTemplates.id })
      .from(schema.invoiceTemplates)
      .where(and(eq(schema.invoiceTemplates.orgId, orgId), eq(schema.invoiceTemplates.name, "Modern")))
      .limit(1);

    if (modern[0]) {
      await db
        .update(schema.invoiceTemplates)
        .set({ isDefault: true, updatedAt: new Date() })
        .where(
          and(
            eq(schema.invoiceTemplates.orgId, orgId),
            eq(schema.invoiceTemplates.id, modern[0].id),
          ),
        );
    }
  }
}
